<a href="https://colab.research.google.com/github/nugi-ML/Dasar-Python/blob/main/14_Fundamental_Matriks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Fundamental Matriks

1. Matriks adalah kumpulan data yang diatur dalam bentuk tabel dua dimensi dengan setiap elemennya terdefinisi berdasarkan baris dan kolom.
2. Setiap elemen matriks dapat diakses melalui metode indexing jika kedua indeks telah diketahui.
3. Elemen matriks dideklarasikan memiliki tipe homogen yang artinya elemen tersebut harus mempunyai tipe data yang sama. Jika elemen tersebut adalah bilangan real, seluruh elemen lainnya pun adalah bilangan real. Walaupun dalam list Python Anda dapat membuat matriks dengan tipe data berbeda, alangkah lebih baik jika tetap mengikuti aturan ini.

In [1]:
matriks = [[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]

print(matriks)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


Library NumPy sering dipakai oleh programmer Python untuk melakukan tugas-tugas dalam ranah science dan engineering karena dianggap memiliki penggunaan penyimpanan memori yang efisien.

Mari lanjutkan dengan implementasi matriks menggunakan NumPy.

In [3]:
import numpy

matriks = numpy.array([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8 ,9]])
print(matriks)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Sekarang, mari bandingkan ukuran memori yang digunakan jika kita menggunakan matriks Python dan matriks NumPy.

In [4]:
import numpy
import sys

var_list= [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
var_array= numpy.array([[1, 2, 3], [4, 5, 6], [7, 8 ,9]])

print("Ukuran keseluruhan elemen list dalam bytes = ",sys.getsizeof(var_list)*len(var_list))
print("Ukuran keseluruhan elemen NumPy dalam bytes = ", var_array.size*var_array.itemsize)

Ukuran keseluruhan elemen list dalam bytes =  240
Ukuran keseluruhan elemen NumPy dalam bytes =  72


# Implementasi Matriks pada Python

## Deklarasi Matriks

Ada dua cara untuk mendeklarasikan matriks menggunakan Python sebagai berikut.

### Deklarasi sekaligus inisialisasi nilai matriks

Cara pertama adalah mendeklarasikan matriks sekaligus menginisialisasikan nilainya dengan ukuran N baris dan M Kolom (NxM). Cara ini dilakukan jika kita telah mengetahui nilai yang perlu diberikan.

In [5]:
matriks = [[1, 0, 0, 0, 0],
            [0, 1, 0, 0, 0],
            [0, 0, 1, 0, 0],
            [0, 0, 0, 1, 0],
            [0, 0, 0, 0, 1]]

print(matriks)

[[1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 1, 0], [0, 0, 0, 0, 1]]


### Deklarasi dengan nilai default.

Cara kedua adalah mendeklarasikan matriks dengan nilai default. Sebagaimana materi array, nilai default ditentukan oleh kesepakatan bersama sesuai kebutuhan dengan nilainya di luar rentang yang ditentukan.

In [6]:
matriks = [[0 for j in range(4)] for i in range(3)]

print(matriks)

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]


## Akses Elemen Matriks

Kita akan mengakses elemen matriks menggunakan metode indexing. Ini artinya Anda perlu mengetahui indeks dari baris dan kolom yang ingin diakses. Berikut adalah struktur untuk mengakses elemen matriks dengan metode indexing.

```
namamatriks[n-baris][n-kolom]
```

In [7]:
var_mat = [[1, 2, 3, 4, 5],
           [6, 7, 8, 9, 10],
           [11, 12, 13, 14, 15],
           [16, 17, 18, 19, 20],
           [21, 22, 23, 24, 25]]

print(var_mat[2][1])

12


# Operasi Matriks pada Python

In [8]:
# Membuat matriks 2x2
var_mat = [[5, 0],
          [1, -2]]
def_mat = [[0 for j in range(2)] for i in range(2)]

for i in range(len(var_mat)):
  for j in range(len(var_mat[0])):
    def_mat[i][j] = var_mat[i][j]*2

print(def_mat)

[[10, 0], [2, -4]]


Phew, materi kali ini sangat erat dengan perhitungan matematika. Cara yang kita pelajari di atas terbilang cukup rumit. Nah, sebenarnya ada cara yang lebih efektif, yaitu dengan menggunakan library NumPy. Perhatikan kode di bawah ini.

In [9]:
import numpy as np

var_mat = np.array([[5, 0],
                    [1, -2]])

result = var_mat * 2

print(result)

[[10  0]
 [ 2 -4]]
